### ISSUE TITLE
Important🔥: .env 작성 및 ormconfig

### ISSUE THREAD

**Issue by lcomment** [3rd-wanted-pre-onboarding-team-D/02-PayHere-wanted-D#3]
## .env 양식
DB_HOST=
DB_USERNAME=
DB_PASSWORD=
DB_DATABASE=
JWT_ACCESS_TOKEN_SECRET=
JWT_ACCESS_TOKEN_EXPIRATION_TIME=
JWT_REFRESH_TOKEN_SECRET=
JWT_REFRESH_TOKEN_EXPIRATION_TIME=

## ormconfig.ts
TypeOrmModuleOptions 중 synchronize 옵션은 처음에만 true, 그 다음부터는 false

**Comment by YongsHub** [comment]
JWT_ACCESS_TOKEN_SECRET=
JWT_ACCESS_TOKEN_EXPIRATION_TIME=
JWT_REFRESH_TOKEN_SECRET=
JWT_REFRESH_TOKEN_EXPIRATION_TIME=
